# Generated by Django 3.2.7 on 2021-09-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='country',
            new_name='countries',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
