# Generated by Django 3.2.7 on 2021-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0002_auto_20210924_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='date',
            field=models.CharField(max_length=5000),
        ),
    ]
