# Generated by Django 3.2.7 on 2021-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0004_rename_type_sales_typess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='date',
            field=models.IntegerField(max_length=5000),
        ),
    ]
