# Generated by Django 3.2.7 on 2021-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportapp', '0005_alter_year_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='date',
            field=models.IntegerField(),
        ),
    ]
